### ISSUE TITLE
C-1.1.23 is failing when it should not be

### ISSUE THREAD

**Issue by pkaeding** [mitre/canonical-ubuntu-18.04-lts-server-cis-baseline#2]
I have a failing test for control 1.1.23: Disable USB Storage. 
```
  ×  C-1.1.23: Disable USB Storage (1 failed)
     ✔  Kernel Module usb-storage is expected not to be loaded
     ×  Kernel Module usb-storage is expected to be disabled
     expected `Kernel Module usb-storage.disabled?` to be truthy, got false
```

However, the 'check' commands indicate that this should not fail:
```
~ $ modprobe -n -v usb-storage
install /bin/true
~ $ lsmod | grep usb-storage
```

The other disabled module checks are working as expected. Could this have to do with the fact that there is a hyphen in the name of the module? Looking at the [`disabled?`](https://github.com/inspec/inspec/blob/49b7d1033dcee2133be4a5f25490174b09cc83e6/lib/inspec/resources/kernel_module.rb#L59-L61) check, it seems that it runs `modprobe --showconfig`, which returns the following line (among others): 

```
install usb_storage /bin/true
```

Note the `_`, instead of the `-` that the docs for this control mention (and the official CIS Benchmark PDF also uses `-` when discussing this control). Are the `-` and `_` interchangeable here? Should the inspec `kernel_module` constructor use the `_` form?

**Comment by aaronlippold** [comment]
Hi, I’m not sure if it’s irrelevant when it comes to the system level service understanding you mean the same thing but I’m sure the ruby code is just using a simple match? or include? Truth be told I don’t remember which function i used. I think the best path would be to update the control to just use the standard naming convention. I’m not sure updating the resource to be more flexible would be the best idea given that what if there is a service where that distinction is important. Would be trading one corner case for another. So a quick PR with an update to the control will probably get it passing again.

**Comment by aaronlippold** [comment]
https://github.com/inspec/inspec/blob/master/lib/inspec/resources/kernel_module.rb#L42-L65
